# -*- coding: utf-8 -*-
"""UAS Praktikum_G231210151.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xjiz__Zb1_xNWJCwWiuFTE7AP0TXNSHq

**NAMA : DIKY ANDRIANTO**
<br>**NIM : G.231.21.0151**</br>
**TEKNIK INFORMATIKA B SORE**
<br>**UAS PRAKTIKUM**</br>
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('stock.csv')

data

"""a. Distribusi data pada setiap atribut Purchase Price, Current Price dan Gain/Loss dengan grafik histogram

"""

plt.figure(figsize=(12, 6))

plt.subplot(1, 3, 1)
plt.hist(data['Purchase Price'], bins=10, edgecolor='black')
plt.xlabel('Purchase Price')
plt.ylabel('Frequency')
plt.title('Histogram of Purchase Price')

plt.subplot(1, 3, 2)
plt.hist(data['Current Price'], bins=10, edgecolor='black')
plt.xlabel('Current Price')
plt.ylabel('Frequency')
plt.title('Histogram of Current Price')

plt.subplot(1, 3, 3)
plt.hist(data['Gain/Loss'], bins=10, edgecolor='black')
plt.xlabel('Gain/Loss')
plt.ylabel('Frequency')
plt.title('Histogram of Gain/Loss')

plt.tight_layout()
plt.show()

"""b. Atribut Stock Name dan Symbol yang memiliki Dividen / Share 5 tertinggi"""

top_dividend = data.nlargest(5, 'Dividend/share')[['Stock Name', 'Symbol', 'Dividend/share']]
print('Atribut Stock Name dan Symbol yang memiliki Dividen / Share 5 tertinggi:')
print(top_dividend)

"""c. Atribut Stock Name dan Symbol yang memiliki Market Value 5 tertinggi"""

top_market_value = data.nlargest(5, 'Market Value')[['Stock Name', 'Symbol', 'Market Value']]
print('\nAtribut Stock Name dan Symbol yang memiliki Market Value 5 tertinggi:')
print(top_market_value)

"""d. Atribut Stock Name dan Symbol yang memiliki Annual Yield 7 tertinggi"""

top_annual_yield = data.nlargest(7, 'Annual Yield')[['Stock Name', 'Symbol', 'Annual Yield']]
print('\nAtribut Stock Name dan Symbol yang memiliki Annual Yield 7 tertinggi:')
print(top_annual_yield)